version: "3.1"

services:
  db:
    image: postgres
    restart: always
    depends_on:
      - adminer
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  next:
    image: nextapp
    depends_on:
      - db
      - adminer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
